[package]
name = "jp-holiday"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
encoding_rs = "0.8.34"
redis = "0.26.1"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking"] }
tokio = { version = "1.39.3", features = ["full"] }
tokio-macros = "2.4.0"
